
version: "3.7"
services:
  webmd-rest-service:
    build: ../../../
    image: 363852383723.dkr.ecr.us-east-1.amazonaws.com/webmd-rest-service:0.1.0
    ports:
    - 8080:8080
    env_file:
    - hidden.env
    labels:
      aws.ecs.fargate.deploy: 1
    #x-fargate-secrets:
      #KEY: value
