version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18

jobs:
  unit-test:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:unit
      - run: yarn test:integration

workflows:
  version: 2
  provisioning:
    jobs:
      - unit-test:
          filters:
            tags:
              only: /^.*/
